version: "3.3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django573
      MYSQL_USER: sahin
      MYSQL_PASSWORD: sahin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    expose:
      # Opens port 3306 on the container
      - '3306'
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: mybrain
    volumes:
      - .:/mybrain
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
