# Generated by Django 4.1.3 on 2022-11-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="message",
            field=models.TextField(max_length=1000),
        ),
    ]
